In [ ]:
# setup and imports
import numpy as np
import time
import sys
import pandas as pd

print(f"Numpy Version: {np.__version__}")

Numpy Version: 2.0.2


## **Section 2: Array Creation (9 Different Methods)**

In [ ]:
# 1. From Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("1. From list:", arr1)

1. From list: [1 2 3 4 5]


In [ ]:
# 2. Zeros array
arr2 = np.zeros((3, 4))
print("\n2. Zeros:\n", arr2)




2. Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 3. Ones array
arr3 = np.ones((2, 3))
print("\n3. Ones:\n", arr3)


3. Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 4. Identity matrix
arr4 = np.eye(4)
print("\n4. Identity matrix:\n", arr4)


4. Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 5. Range with arange
arr5 = np.arange(0, 20, 2)
print("\n5. Arange (0-20 step 2):", arr5)


5. Arange (0-20 step 2): [ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# 6. Linear space
arr6 = np.linspace(0, 1, 5)
print("\n6. Linspace (5 points 0-1):", arr6)   # start=1, end=1, space=5


6. Linspace (5 points 0-1): [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# 7. Random integers
arr7 = np.random.randint(1, 100, size=(3, 3))
print("\n7. Random integers:\n", arr7)
# (start, stop, size)


7. Random integers:
 [[ 5 75 97]
 [69 29 70]
 [35 26 46]]


In [ ]:
# 8. Random normal distribution
arr8 = np.random.normal(loc=0, scale=1, size=10)
print("\n8. Normal distribution:", arr8)


8. Normal distribution: [ 1.42697153  0.11864754  0.08043997  1.61127661 -0.35926269  0.52855366
  1.40359339  0.20197261 -0.66628747  1.09395167]


In [ ]:
# 9. Full array (constant value)
arr9 = np.full((2, 4), 22)
print("\n9. Full array (all 42s):\n", arr9)


9. Full array (all 42s):
 [[22 22 22 22]
 [22 22 22 22]]


In [ ]:
# 10. Uniform random distribution
arr10 = np.random.uniform(low=0, high=1, size=(3, 3))
print("\n10. Uniform Random distribution:\n", arr10)


10. Uniform Random distribution:
 [[0.58280936 0.01135375 0.12455562]
 [0.39348652 0.0096171  0.74443307]
 [0.0720286  0.68377309 0.92330425]]


## **Section 3: Array Properties**

In [ ]:
# Create a sample array
sample = np.random.randint(1, 100, size=(4, 5))

print(f"Array:\n{sample}")
print(f"\nShape: {sample.shape}")
print(f"Dimensions (ndim): {sample.ndim}")
print(f"Total elements (size): {sample.size}")
print(f"Data type (dtype): {sample.dtype}")
print(f"Item size (bytes): {sample.itemsize}")
print(f"Total memory (bytes): {sample.nbytes}")

Array:
[[62  5 92 55 71]
 [84 76 99 59 25]
 [ 2 65 99 95 76]
 [39  1 31 12 19]]

Shape: (4, 5)
Dimensions (ndim): 2
Total elements (size): 20
Data type (dtype): int64
Item size (bytes): 8
Total memory (bytes): 160


## **Section 4: Indexing and Slicing**

In [ ]:
# Create a 2D array
matrix = np.array([[10, 20, 30, 40],
                   [50, 60, 70, 80],
                   [90, 100, 110, 120]])

print("Original matrix:")
print(matrix)

Original matrix:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [ ]:
# Basic indexing
print(f"\nElement at [1, 2]: {matrix[1, 2]}")  # Row 1, Col 2
print(f"First row: {matrix[0]}")
print(f"Last column: {matrix[:, -1]}")


Element at [1, 2]: 70
First row: [10 20 30 40]
Last column: [ 40  80 120]


In [ ]:
# Slicing
print(f"\nFirst 2 rows, first 3 columns:\n{matrix[:2, :3]}")
print(f"Every other row, all columns:\n{matrix[::2, :]}")


First 2 rows, first 3 columns:
[[10 20 30]
 [50 60 70]]
Every other row, all columns:
[[ 10  20  30  40]
 [ 90 100 110 120]]


In [ ]:
# Fancy indexing
rows = [0, 2]
cols = [1, 3]
print(f"\nElements at (0,1) and (2,3): {matrix[rows, cols]}")


Elements at (0,1) and (2,3): [ 20 120]


In [ ]:

# Boolean masking
mask = matrix > 50
print(f"\nBoolean mask:\n{mask}")
print(f"Elements > 50: {matrix[mask]}")


Boolean mask:
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Elements > 50: [ 60  70  80  90 100 110 120]


## **Section 5: Reshaping and Manipulation**

In [ ]:
# Create a 1D array
arr = np.arange(12)
print(f"Original: {arr}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(2, 9, 3)

array([2, 5, 8])

In [ ]:
# Reshape
reshaped = arr.reshape(3, 4)
print(f"Reshaped to (3,4):\n{reshaped}")


Reshaped to (3,4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr.reshape(6, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# Flatten (returns copy)
flattened = reshaped.flatten()
print(f"Flattened: {flattened}")


Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Ravel (returns view when possible)
raveled = reshaped.ravel()
print(f"Raveled: {raveled}")

Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [ ]:
# Both are equivalent:
flat_view = np.ravel(arr)
flat_method = arr.ravel()
print(flat_view)
print(flat_method)

[1 2 3 4]
[1 2 3 4]


In [ ]:
# Transpose
transposed = reshaped.T
print(f"Transposed (4,3):\n{transposed}")

Transposed (4,3):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# Resize (modifies original)
arr_resized = np.resize(arr, (2, 8))
print(f"Resized to (2,8):\n{arr_resized}")

Resized to (2,8):
[[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]


In [ ]:
arr

array([[1, 2],
       [3, 4]])

In [ ]:
# stacking
arr_a = np.array([[2, 3], [4, 5]])
arr_b = np.array([[4, 7], [9, 3]])

# Horizontal Stack
h_stacked = np.hstack((arr_a, arr_b))
print(f"Horizontal Stack:\n{h_stacked}")

# Vertical Stack
v_stacked = np.vstack((arr_a, arr_b))
print(f"Vertical Stack:\n{v_stacked}")

Horizontal Stack:
[[2 3 4 7]
 [4 5 9 3]]
Vertical Stack:
[[2 3]
 [4 5]
 [4 7]
 [9 3]]


In [ ]:
arr_a

array([[2, 3],
       [4, 5]])

## **Section 6: Mathematical and Statistical Operations**

In [ ]:
# Create sample data
data = np.random.randint(1, 100, size=(5, 5))
print("Sample data:\n", data)

# Element-wise operations
print(f"\nAdd 10:\n{data + 10}")
print(f"Square each element:\n{data ** 2}")
print(f"Multiply by 2:\n{data * 2}")

# Axis-wise operations
print(f"\nSum of all elements: {np.sum(data)}")
print(f"Sum along rows (axis=1): {np.sum(data, axis=1)}")
print(f"Sum along columns (axis=0): {np.sum(data, axis=0)}")

# Statistical operations
print(f"\nMean: {np.mean(data):.2f}")
print(f"Median: {np.median(data):.2f}")
print(f"Standard deviation: {np.std(data):.2f}")
print(f"Variance: {np.var(data):.2f}")
print(f"Min value: {np.min(data)}")
print(f"Max value: {np.max(data)}")
print(f"Range (max-min): {np.ptp(data)}")

# Percentiles
print(f"25th percentile: {np.percentile(data, 25)}")
print(f"75th percentile: {np.percentile(data, 75)}")

Sample data:
 [[11 22 68 75 76]
 [ 8 31 80 18  8]
 [39 98 68 95  2]
 [84 47 62 47 96]
 [31 82  8 45 54]]

Add 10:
[[ 21  32  78  85  86]
 [ 18  41  90  28  18]
 [ 49 108  78 105  12]
 [ 94  57  72  57 106]
 [ 41  92  18  55  64]]
Square each element:
[[ 121  484 4624 5625 5776]
 [  64  961 6400  324   64]
 [1521 9604 4624 9025    4]
 [7056 2209 3844 2209 9216]
 [ 961 6724   64 2025 2916]]
Multiply by 2:
[[ 22  44 136 150 152]
 [ 16  62 160  36  16]
 [ 78 196 136 190   4]
 [168  94 124  94 192]
 [ 62 164  16  90 108]]

Sum of all elements: 1255
Sum along rows (axis=1): [252 145 302 336 220]
Sum along columns (axis=0): [173 280 286 280 236]

Mean: 50.20
Median: 47.00
Standard deviation: 30.62
Variance: 937.76
Min value: 2
Max value: 98
Range (max-min): 96
25th percentile: 22.0
75th percentile: 76.0


## **Section 7: Broadcasting**

In [ ]:
# Broadcasting example 1: Scalar + Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array (3x2):\n{arr}")
print(f"Array + 10:\n{arr + 10}")  # Scalar broadcasted to all elements

# Broadcasting example 2: 1D + 2D
row_vector = np.array([1, 2, 3])
matrix = np.array([[10, 20, 30], [40, 50, 60]])
print(f"\nMatrix:\n{matrix}")
print(f"Row vector: {row_vector}")
print(f"Matrix + Row vector:\n{matrix + row_vector}")

# Broadcasting example 3: Column vector + Row vector
col_vector = np.array([[1], [2], [3]])  # Shape (3,1)
row_vector = np.array([10, 20, 30])      # Shape (3,)
print(f"\nColumn vector (3,1):\n{col_vector}")
print(f"Row vector (3,): {row_vector}")
print(f"Broadcasted result (3,3):\n{col_vector + row_vector}")

# Broadcasting rules demonstration
print("\n--- Broadcasting Rules ---")
print("Rule 1: If dimensions differ, prepend 1s to smaller shape")
print("Rule 2: Compatible if dimensions equal or one is 1")
print("Rule 3: After broadcasting, shape is max of input shapes")

Array (3x2):
[[1 2 3]
 [4 5 6]]
Array + 10:
[[11 12 13]
 [14 15 16]]

Matrix:
[[10 20 30]
 [40 50 60]]
Row vector: [1 2 3]
Matrix + Row vector:
[[11 22 33]
 [41 52 63]]

Column vector (3,1):
[[1]
 [2]
 [3]]
Row vector (3,): [10 20 30]
Broadcasted result (3,3):
[[11 21 31]
 [12 22 32]
 [13 23 33]]

--- Broadcasting Rules ---
Rule 1: If dimensions differ, prepend 1s to smaller shape
Rule 2: Compatible if dimensions equal or one is 1
Rule 3: After broadcasting, shape is max of input shapes


## **Section 8: Performance Comparison (NumPy vs Python Lists)**

In [ ]:
import time

def performance_comparison():
    sizes = [1000, 10000, 100000, 1000000]
    results = []

    for size in sizes:
        print(f"\n--- Testing with size: {size} ---")

        # 1. Element-wise addition
        # Python list approach
        list1 = list(range(size))
        list2 = list(range(size))
        start = time.time()
        list_result = [x + y for x, y in zip(list1, list2)]
        list_time = time.time() - start

        # NumPy approach
        arr1 = np.arange(size)
        arr2 = np.arange(size)
        start = time.time()
        numpy_result = arr1 + arr2
        numpy_time = time.time() - start

        speedup = list_time / numpy_time if numpy_time > 0 else float('inf')

        print(f"Python list time: {list_time:.6f} sec")
        print(f"NumPy time: {numpy_time:.6f} sec")
        print(f"Speedup: {speedup:.2f}x")

        results.append({
            'size': size,
            'list_time': list_time,
            'numpy_time': numpy_time,
            'speedup': speedup
        })

        # 2. Sum operation
        start = time.time()
        sum(list1)
        list_sum_time = time.time() - start

        start = time.time()
        np.sum(arr1)
        numpy_sum_time = time.time() - start

        print(f"Python sum time: {list_sum_time:.6f} sec")
        print(f"NumPy sum time: {numpy_sum_time:.6f} sec")
        print(f"Speedup: {list_sum_time/numpy_sum_time:.2f}x")

    return results

performance_results = performance_comparison()


--- Testing with size: 1000 ---
Python list time: 0.000076 sec
NumPy time: 0.000019 sec
Speedup: 4.03x
Python sum time: 0.000008 sec
NumPy sum time: 0.000033 sec
Speedup: 0.25x

--- Testing with size: 10000 ---
Python list time: 0.000416 sec
NumPy time: 0.000009 sec
Speedup: 44.72x
Python sum time: 0.000074 sec
NumPy sum time: 0.000015 sec
Speedup: 4.94x

--- Testing with size: 100000 ---
Python list time: 0.004176 sec
NumPy time: 0.000237 sec
Speedup: 17.64x
Python sum time: 0.000785 sec
NumPy sum time: 0.000062 sec
Speedup: 12.66x

--- Testing with size: 1000000 ---
Python list time: 0.041313 sec
NumPy time: 0.001967 sec
Speedup: 21.00x
Python sum time: 0.007644 sec
NumPy sum time: 0.000537 sec
Speedup: 14.23x


## **Section 9: Memory Comparison**

In [ ]:
def memory_comparison():
    size = 1000000

    # Python list
    py_list = list(range(size))
    list_memory = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)

    # NumPy array (int32)
    np_array_int32 = np.arange(size, dtype=np.int32)
    numpy_memory_int32 = np_array_int32.nbytes

    # NumPy array (float64)
    np_array_float64 = np.arange(size, dtype=np.float64)
    numpy_memory_float64 = np_array_float64.nbytes

    print(f"Python list memory: {list_memory / 1024 / 1024:.2f} MB")
    print(f"NumPy int32 memory: {numpy_memory_int32 / 1024 / 1024:.2f} MB")
    print(f"NumPy float64 memory: {numpy_memory_float64 / 1024 / 1024:.2f} MB")
    print(f"\nNumPy int32 is {list_memory/numpy_memory_int32:.1f}x more memory efficient!")

memory_comparison()

Python list memory: 34.33 MB
NumPy int32 memory: 3.81 MB
NumPy float64 memory: 7.63 MB

NumPy int32 is 9.0x more memory efficient!


# Section 10: Save and Load Operations

In [ ]:
# Create some arrays to save
arr1 = np.random.randint(1, 100, size=(5, 5))
arr2 = np.linspace(0, 1, 100)
arr3 = np.eye(10)

# Save single array
np.save('saved_array.npy', arr1)
print("Saved arr1 to 'saved_array.npy'")

# Load single array
loaded_arr = np.load('saved_array.npy')
print(f"Loaded array:\n{loaded_arr}")

# Save multiple arrays in compressed format
np.savez_compressed('multiple_arrays.npz',
                    matrix=arr1,
                    sequence=arr2,
                    identity=arr3)
print("Saved multiple arrays to 'multiple_arrays.npz'")

# Load multiple arrays
loaded = np.load('multiple_arrays.npz')
print(f"Loaded matrix shape: {loaded['matrix'].shape}")
print(f"Loaded sequence shape: {loaded['sequence'].shape}")
print(f"Loaded identity shape: {loaded['identity'].shape}")

# Save as text file (CSV)
np.savetxt('array_export.csv', arr1, delimiter=',', fmt='%d')
print("Saved as CSV: 'array_export.csv'")

# Load from CSV
csv_loaded = np.loadtxt('array_export.csv', delimiter=',')
print(f"Loaded from CSV shape: {csv_loaded.shape}")

Saved arr1 to 'saved_array.npy'
Loaded array:
[[98 72 30 35 77]
 [74 32 67 18 53]
 [50 95 49 57 64]
 [54 13 16 61 93]
 [ 7 85 16 84 71]]
Saved multiple arrays to 'multiple_arrays.npz'
Loaded matrix shape: (5, 5)
Loaded sequence shape: (100,)
Loaded identity shape: (10, 10)
Saved as CSV: 'array_export.csv'
Loaded from CSV shape: (5, 5)


In [2]:
import numpy as np
# Create a realistic sales dataset
np.random.seed(42)
months = 12
products = 5

# Generate sales data (rows=months, columns=products)
sales_data = np.random.randint(100, 1000, size=(months, products))

# Add some seasonal pattern
seasonal_boost = np.array([1.0, 1.0, 1.2, 1.3, 1.4, 1.5,
                           1.4, 1.3, 1.2, 1.1, 1.5, 1.8]).reshape(12, 1)
sales_data = (sales_data * seasonal_boost).astype(int)

print("=== Sales Data Analysis ===")
print(f"Sales data shape: {sales_data.shape}")
print(f"Total sales (all products, all months): ${np.sum(sales_data):,}")
print(f"Average monthly sales: ${np.mean(sales_data, axis=0)}")
print(f"Best performing product: Product {np.argmax(np.sum(sales_data, axis=0)) + 1}")

# Find top 3 months
monthly_totals = np.sum(sales_data, axis=1)
top_months = np.argsort(monthly_totals)[-3:][::-1]
print(f"\nTop 3 months (0=Jan, 11=Dec): {top_months}")
print(f"Top month sales: ${monthly_totals[top_months[0]]:,}")

# Product performance over time
print(f"\nProduct trends (growth from month 1 to 12):")
for p in range(products):
    growth = (sales_data[-1, p] - sales_data[0, p]) / sales_data[0, p] * 100
    print(f"Product {p+1}: {growth:.1f}% growth")

=== Sales Data Analysis ===
Sales data shape: (12, 5)
Total sales (all products, all months): $42,380
Average monthly sales: $[681.58333333 871.66666667 731.41666667 731.83333333 515.16666667]
Best performing product: Product 2

Top 3 months (0=Jan, 11=Dec): [11  8  4]
Top month sales: $5,380

Product trends (growth from month 1 to 12):
Product 1: 717.8% growth
Product 2: 150.8% growth
Product 3: -77.5% growth
Product 4: 357.3% growth
Product 5: 132.0% growth


In [3]:
sales_data

array([[ 202,  535,  960,  370,  206],
       [ 171,  800,  120,  714,  221],
       [ 679,  376,  516,  669,  224],
       [ 613,  258, 1262,  991,  299],
       [1065,  571, 1216,  620,  827],
       [ 769, 1357,  727,  436,  564],
       [ 364,  782,  578,  169,  492],
       [1101, 1242,  858,  746,  205],
       [ 732,  937,  690,  958, 1058],
       [ 317,  864,  728, 1072,  732],
       [ 514, 1396,  906,  345,  876],
       [1652, 1342,  216, 1692,  478]])